### ISSUE TITLE
[TODO] setup benchmarks over time

### ISSUE THREAD

**Issue by erwanp** [radis/radis-benchmark#1]
We'll use ASV

See example for astropy : 
https://www.astropy.org/astropy-benchmarks

Todo : 

- [x] setup asv locally
- [x] write benchmarks : https://asv.readthedocs.io/en/stable/writing_benchmarks.html#writing-benchmarks
- [x] run benchmarks for all commits 
- [x] serve online   : https://radis.github.io/radis-benchmark/
